/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.2.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionConnect;
    QAction *actionDisconnect;
    QAction *actionQuit;
    QWidget *centralWidget;
    QPushButton *startButton;
    QPushButton *recalButton;
    QPushButton *stopButton;
    QLabel *pulseRateLabel;
    QLabel *pulsePressureLabel;
    QFrame *resp;
    QLabel *respLabel;
    QPushButton *respIcon;
    QLabel *respValue;
    QFrame *hr;
    QLabel *hrLabel;
    QPushButton *hrIcon;
    QLabel *hrValue;
    QFrame *frame;
    QFrame *frame_2;
    QFrame *vitalsFrame;
    QFrame *batt;
    QLabel *battLabel;
    QLabel *battValue;
    QPushButton *battIconx;
    QPushButton *battIcon0;
    QPushButton *battIcon1;
    QPushButton *battIcon2;
    QPushButton *battIcon3;
    QPushButton *battIcon4;
    QPushButton *battIcon5;
    QPushButton *battIcon6;
    QPushButton *battIcon7;
    QPushButton *battIcon8;
    QPushButton *battIcon9;
    QPushButton *battIcon10;
    QFrame *snr;
    QLabel *snrLabel;
    QLabel *snrValue;
    QPushButton *snrIcon0;
    QPushButton *snrIcon1;
    QPushButton *snrIcon2;
    QPushButton *snrIcon3;
    QPushButton *snrIcon4;
    QPushButton *snrIcon5;
    QPushButton *snrIcon6;
    QPushButton *snrIcon7;
    QPushButton *snrIcon8;
    QPushButton *snrIcon9;
    QPushButton *snrIcon10;
    QFrame *cuff;
    QLabel *cuffLabel;
    QLabel *cuffValue;
    QFrame *target;
    QLabel *targetLabel;
    QLabel *targetValue;
    QPushButton *targetPlus;
    QPushButton *targetMinus;
    QFrame *map;
    QLabel *mapLabel;
    QPushButton *mapIcon;
    QLabel *mapValue;
    QFrame *bp;
    QLabel *bpLabel;
    QPushButton *bpIcon;
    QLabel *bpValue;
    QMenuBar *menuBar;
    QMenu *menuCaretaker_4_Demo_App;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(477, 610);
        MainWindow->setAutoFillBackground(true);
        actionConnect = new QAction(MainWindow);
        actionConnect->setObjectName(QStringLiteral("actionConnect"));
        actionDisconnect = new QAction(MainWindow);
        actionDisconnect->setObjectName(QStringLiteral("actionDisconnect"));
        actionQuit = new QAction(MainWindow);
        actionQuit->setObjectName(QStringLiteral("actionQuit"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        startButton = new QPushButton(centralWidget);
        startButton->setObjectName(QStringLiteral("startButton"));
        startButton->setGeometry(QRect(70, 520, 99, 31));
        startButton->setFocusPolicy(Qt::NoFocus);
        QIcon icon;
        icon.addFile(QStringLiteral(":/res/btn_start_default.png"), QSize(), QIcon::Normal, QIcon::Off);
        startButton->setIcon(icon);
        startButton->setIconSize(QSize(32, 32));
        recalButton = new QPushButton(centralWidget);
        recalButton->setObjectName(QStringLiteral("recalButton"));
        recalButton->setGeometry(QRect(190, 520, 99, 31));
        recalButton->setFocusPolicy(Qt::NoFocus);
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/res/btn_recal_default.png"), QSize(), QIcon::Normal, QIcon::Off);
        recalButton->setIcon(icon1);
        recalButton->setIconSize(QSize(32, 32));
        stopButton = new QPushButton(centralWidget);
        stopButton->setObjectName(QStringLiteral("stopButton"));
        stopButton->setGeometry(QRect(310, 520, 99, 31));
        stopButton->setFocusPolicy(Qt::NoFocus);
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/res/btn_stop_default.png"), QSize(), QIcon::Normal, QIcon::Off);
        stopButton->setIcon(icon2);
        stopButton->setIconSize(QSize(32, 32));
        pulseRateLabel = new QLabel(centralWidget);
        pulseRateLabel->setObjectName(QStringLiteral("pulseRateLabel"));
        pulseRateLabel->setGeometry(QRect(190, 10, 81, 17));
        pulseRateLabel->setStyleSheet(QStringLiteral("QLabel { background-color : black ; color : white; }"));
        pulseRateLabel->setTextFormat(Qt::AutoText);
        pulsePressureLabel = new QLabel(centralWidget);
        pulsePressureLabel->setObjectName(QStringLiteral("pulsePressureLabel"));
        pulsePressureLabel->setGeometry(QRect(180, 170, 111, 17));
        pulsePressureLabel->setStyleSheet(QStringLiteral("QLabel { background-color : black ; color : white; }"));
        pulsePressureLabel->setTextFormat(Qt::AutoText);
        resp = new QFrame(centralWidget);
        resp->setObjectName(QStringLiteral("resp"));
        resp->setGeometry(QRect(20, 330, 80, 80));
        resp->setFrameShape(QFrame::StyledPanel);
        resp->setFrameShadow(QFrame::Raised);
        respLabel = new QLabel(resp);
        respLabel->setObjectName(QStringLiteral("respLabel"));
        respLabel->setGeometry(QRect(30, 10, 41, 17));
        respIcon = new QPushButton(resp);
        respIcon->setObjectName(QStringLiteral("respIcon"));
        respIcon->setGeometry(QRect(10, 10, 21, 16));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        respIcon->setPalette(palette);
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/res/icon_respiration.png"), QSize(), QIcon::Normal, QIcon::Off);
        respIcon->setIcon(icon3);
        respValue = new QLabel(resp);
        respValue->setObjectName(QStringLiteral("respValue"));
        respValue->setGeometry(QRect(10, 30, 61, 41));
        QFont font;
        font.setPointSize(26);
        font.setBold(true);
        font.setWeight(75);
        respValue->setFont(font);
        respValue->setAlignment(Qt::AlignCenter);
        hr = new QFrame(centralWidget);
        hr->setObjectName(QStringLiteral("hr"));
        hr->setGeometry(QRect(110, 330, 80, 80));
        hr->setFrameShape(QFrame::StyledPanel);
        hr->setFrameShadow(QFrame::Raised);
        hrLabel = new QLabel(hr);
        hrLabel->setObjectName(QStringLiteral("hrLabel"));
        hrLabel->setGeometry(QRect(35, 10, 31, 16));
        hrIcon = new QPushButton(hr);
        hrIcon->setObjectName(QStringLiteral("hrIcon"));
        hrIcon->setGeometry(QRect(10, 10, 21, 16));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        hrIcon->setPalette(palette1);
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/res/icon_heart_rate.png"), QSize(), QIcon::Normal, QIcon::Off);
        hrIcon->setIcon(icon4);
        hrValue = new QLabel(hr);
        hrValue->setObjectName(QStringLiteral("hrValue"));
        hrValue->setGeometry(QRect(10, 30, 61, 41));
        hrValue->setFont(font);
        hrValue->setAlignment(Qt::AlignCenter);
        frame = new QFrame(centralWidget);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(10, 0, 461, 151));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(10, 160, 461, 151));
        frame_2->setAutoFillBackground(false);
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        vitalsFrame = new QFrame(centralWidget);
        vitalsFrame->setObjectName(QStringLiteral("vitalsFrame"));
        vitalsFrame->setGeometry(QRect(9, 319, 461, 191));
        vitalsFrame->setStyleSheet(QStringLiteral("background-color: black;"));
        vitalsFrame->setFrameShape(QFrame::StyledPanel);
        vitalsFrame->setFrameShadow(QFrame::Raised);
        batt = new QFrame(centralWidget);
        batt->setObjectName(QStringLiteral("batt"));
        batt->setGeometry(QRect(20, 420, 80, 80));
        batt->setFrameShape(QFrame::StyledPanel);
        batt->setFrameShadow(QFrame::Raised);
        battLabel = new QLabel(batt);
        battLabel->setObjectName(QStringLiteral("battLabel"));
        battLabel->setGeometry(QRect(20, 10, 41, 17));
        battValue = new QLabel(batt);
        battValue->setObjectName(QStringLiteral("battValue"));
        battValue->setGeometry(QRect(5, 40, 34, 21));
        QFont font1;
        font1.setPointSize(9);
        font1.setBold(true);
        font1.setWeight(75);
        battValue->setFont(font1);
        battValue->setAlignment(Qt::AlignCenter);
        battIconx = new QPushButton(batt);
        battIconx->setObjectName(QStringLiteral("battIconx"));
        battIconx->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIconx->setPalette(palette2);
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/res/battx.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIconx->setIcon(icon5);
        battIconx->setIconSize(QSize(32, 32));
        battIcon0 = new QPushButton(batt);
        battIcon0->setObjectName(QStringLiteral("battIcon0"));
        battIcon0->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon0->setPalette(palette3);
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/res/batt0.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon0->setIcon(icon6);
        battIcon0->setIconSize(QSize(32, 32));
        battIcon1 = new QPushButton(batt);
        battIcon1->setObjectName(QStringLiteral("battIcon1"));
        battIcon1->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon1->setPalette(palette4);
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/res/batt1.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon1->setIcon(icon7);
        battIcon1->setIconSize(QSize(32, 32));
        battIcon2 = new QPushButton(batt);
        battIcon2->setObjectName(QStringLiteral("battIcon2"));
        battIcon2->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Button, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon2->setPalette(palette5);
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/res/batt2.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon2->setIcon(icon8);
        battIcon2->setIconSize(QSize(32, 32));
        battIcon3 = new QPushButton(batt);
        battIcon3->setObjectName(QStringLiteral("battIcon3"));
        battIcon3->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Button, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon3->setPalette(palette6);
        QIcon icon9;
        icon9.addFile(QStringLiteral(":/res/batt3.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon3->setIcon(icon9);
        battIcon3->setIconSize(QSize(32, 32));
        battIcon4 = new QPushButton(batt);
        battIcon4->setObjectName(QStringLiteral("battIcon4"));
        battIcon4->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Button, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon4->setPalette(palette7);
        QIcon icon10;
        icon10.addFile(QStringLiteral(":/res/batt4.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon4->setIcon(icon10);
        battIcon4->setIconSize(QSize(32, 32));
        battIcon5 = new QPushButton(batt);
        battIcon5->setObjectName(QStringLiteral("battIcon5"));
        battIcon5->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Button, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon5->setPalette(palette8);
        QIcon icon11;
        icon11.addFile(QStringLiteral(":/res/batt5.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon5->setIcon(icon11);
        battIcon5->setIconSize(QSize(32, 32));
        battIcon6 = new QPushButton(batt);
        battIcon6->setObjectName(QStringLiteral("battIcon6"));
        battIcon6->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Button, brush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon6->setPalette(palette9);
        QIcon icon12;
        icon12.addFile(QStringLiteral(":/res/batt6.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon6->setIcon(icon12);
        battIcon6->setIconSize(QSize(32, 32));
        battIcon7 = new QPushButton(batt);
        battIcon7->setObjectName(QStringLiteral("battIcon7"));
        battIcon7->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Button, brush);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon7->setPalette(palette10);
        QIcon icon13;
        icon13.addFile(QStringLiteral(":/res/batt7.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon7->setIcon(icon13);
        battIcon7->setIconSize(QSize(32, 32));
        battIcon8 = new QPushButton(batt);
        battIcon8->setObjectName(QStringLiteral("battIcon8"));
        battIcon8->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Button, brush);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon8->setPalette(palette11);
        QIcon icon14;
        icon14.addFile(QStringLiteral(":/res/batt8.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon8->setIcon(icon14);
        battIcon8->setIconSize(QSize(32, 32));
        battIcon9 = new QPushButton(batt);
        battIcon9->setObjectName(QStringLiteral("battIcon9"));
        battIcon9->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Button, brush);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon9->setPalette(palette12);
        QIcon icon15;
        icon15.addFile(QStringLiteral(":/res/batt9.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon9->setIcon(icon15);
        battIcon9->setIconSize(QSize(32, 32));
        battIcon10 = new QPushButton(batt);
        battIcon10->setObjectName(QStringLiteral("battIcon10"));
        battIcon10->setGeometry(QRect(40, 30, 31, 41));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::Button, brush);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush);
        battIcon10->setPalette(palette13);
        QIcon icon16;
        icon16.addFile(QStringLiteral(":/res/batt10.png"), QSize(), QIcon::Normal, QIcon::Off);
        battIcon10->setIcon(icon16);
        battIcon10->setIconSize(QSize(32, 32));
        snr = new QFrame(centralWidget);
        snr->setObjectName(QStringLiteral("snr"));
        snr->setGeometry(QRect(110, 420, 80, 80));
        snr->setFrameShape(QFrame::StyledPanel);
        snr->setFrameShadow(QFrame::Raised);
        snrLabel = new QLabel(snr);
        snrLabel->setObjectName(QStringLiteral("snrLabel"));
        snrLabel->setGeometry(QRect(20, 10, 41, 17));
        snrValue = new QLabel(snr);
        snrValue->setObjectName(QStringLiteral("snrValue"));
        snrValue->setGeometry(QRect(2, 40, 34, 21));
        snrValue->setFont(font1);
        snrValue->setAlignment(Qt::AlignCenter);
        snrIcon0 = new QPushButton(snr);
        snrIcon0->setObjectName(QStringLiteral("snrIcon0"));
        snrIcon0->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::Button, brush);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon0->setPalette(palette14);
        QIcon icon17;
        icon17.addFile(QStringLiteral(":/res/signal_quality0.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon0->setIcon(icon17);
        snrIcon0->setIconSize(QSize(32, 32));
        snrIcon1 = new QPushButton(snr);
        snrIcon1->setObjectName(QStringLiteral("snrIcon1"));
        snrIcon1->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::Button, brush);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon1->setPalette(palette15);
        QIcon icon18;
        icon18.addFile(QStringLiteral(":/res/signal_quality1.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon1->setIcon(icon18);
        snrIcon1->setIconSize(QSize(32, 32));
        snrIcon2 = new QPushButton(snr);
        snrIcon2->setObjectName(QStringLiteral("snrIcon2"));
        snrIcon2->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::Button, brush);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon2->setPalette(palette16);
        QIcon icon19;
        icon19.addFile(QStringLiteral(":/res/signal_quality2.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon2->setIcon(icon19);
        snrIcon2->setIconSize(QSize(32, 32));
        snrIcon3 = new QPushButton(snr);
        snrIcon3->setObjectName(QStringLiteral("snrIcon3"));
        snrIcon3->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::Button, brush);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon3->setPalette(palette17);
        QIcon icon20;
        icon20.addFile(QStringLiteral(":/res/signal_quality3.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon3->setIcon(icon20);
        snrIcon3->setIconSize(QSize(32, 32));
        snrIcon4 = new QPushButton(snr);
        snrIcon4->setObjectName(QStringLiteral("snrIcon4"));
        snrIcon4->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::Button, brush);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon4->setPalette(palette18);
        QIcon icon21;
        icon21.addFile(QStringLiteral(":/res/signal_quality4.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon4->setIcon(icon21);
        snrIcon4->setIconSize(QSize(32, 32));
        snrIcon5 = new QPushButton(snr);
        snrIcon5->setObjectName(QStringLiteral("snrIcon5"));
        snrIcon5->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::Button, brush);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon5->setPalette(palette19);
        QIcon icon22;
        icon22.addFile(QStringLiteral(":/res/signal_quality5.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon5->setIcon(icon22);
        snrIcon5->setIconSize(QSize(32, 32));
        snrIcon6 = new QPushButton(snr);
        snrIcon6->setObjectName(QStringLiteral("snrIcon6"));
        snrIcon6->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::Button, brush);
        palette20.setBrush(QPalette::Active, QPalette::Base, brush);
        palette20.setBrush(QPalette::Active, QPalette::Window, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon6->setPalette(palette20);
        QIcon icon23;
        icon23.addFile(QStringLiteral(":/res/signal_quality6.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon6->setIcon(icon23);
        snrIcon6->setIconSize(QSize(32, 32));
        snrIcon7 = new QPushButton(snr);
        snrIcon7->setObjectName(QStringLiteral("snrIcon7"));
        snrIcon7->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::Button, brush);
        palette21.setBrush(QPalette::Active, QPalette::Base, brush);
        palette21.setBrush(QPalette::Active, QPalette::Window, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon7->setPalette(palette21);
        QIcon icon24;
        icon24.addFile(QStringLiteral(":/res/signal_quality7.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon7->setIcon(icon24);
        snrIcon7->setIconSize(QSize(32, 32));
        snrIcon8 = new QPushButton(snr);
        snrIcon8->setObjectName(QStringLiteral("snrIcon8"));
        snrIcon8->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::Button, brush);
        palette22.setBrush(QPalette::Active, QPalette::Base, brush);
        palette22.setBrush(QPalette::Active, QPalette::Window, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon8->setPalette(palette22);
        QIcon icon25;
        icon25.addFile(QStringLiteral(":/res/signal_quality8.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon8->setIcon(icon25);
        snrIcon8->setIconSize(QSize(32, 32));
        snrIcon9 = new QPushButton(snr);
        snrIcon9->setObjectName(QStringLiteral("snrIcon9"));
        snrIcon9->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::Button, brush);
        palette23.setBrush(QPalette::Active, QPalette::Base, brush);
        palette23.setBrush(QPalette::Active, QPalette::Window, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon9->setPalette(palette23);
        QIcon icon26;
        icon26.addFile(QStringLiteral(":/res/signal_quality9.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon9->setIcon(icon26);
        snrIcon9->setIconSize(QSize(32, 32));
        snrIcon10 = new QPushButton(snr);
        snrIcon10->setObjectName(QStringLiteral("snrIcon10"));
        snrIcon10->setGeometry(QRect(38, 30, 40, 40));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::Button, brush);
        palette24.setBrush(QPalette::Active, QPalette::Base, brush);
        palette24.setBrush(QPalette::Active, QPalette::Window, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::Window, brush);
        snrIcon10->setPalette(palette24);
        QIcon icon27;
        icon27.addFile(QStringLiteral(":/res/signal_quality10.png"), QSize(), QIcon::Normal, QIcon::Off);
        snrIcon10->setIcon(icon27);
        snrIcon10->setIconSize(QSize(32, 32));
        cuff = new QFrame(centralWidget);
        cuff->setObjectName(QStringLiteral("cuff"));
        cuff->setGeometry(QRect(200, 420, 80, 80));
        cuff->setFrameShape(QFrame::StyledPanel);
        cuff->setFrameShadow(QFrame::Raised);
        cuffLabel = new QLabel(cuff);
        cuffLabel->setObjectName(QStringLiteral("cuffLabel"));
        cuffLabel->setGeometry(QRect(10, 10, 61, 20));
        QFont font2;
        font2.setPointSize(9);
        cuffLabel->setFont(font2);
        cuffValue = new QLabel(cuff);
        cuffValue->setObjectName(QStringLiteral("cuffValue"));
        cuffValue->setGeometry(QRect(5, 30, 70, 41));
        QFont font3;
        font3.setPointSize(24);
        font3.setBold(true);
        font3.setWeight(75);
        cuffValue->setFont(font3);
        cuffValue->setAlignment(Qt::AlignCenter);
        target = new QFrame(centralWidget);
        target->setObjectName(QStringLiteral("target"));
        target->setGeometry(QRect(290, 420, 170, 80));
        target->setFrameShape(QFrame::StyledPanel);
        target->setFrameShadow(QFrame::Raised);
        targetLabel = new QLabel(target);
        targetLabel->setObjectName(QStringLiteral("targetLabel"));
        targetLabel->setGeometry(QRect(40, 10, 101, 20));
        targetValue = new QLabel(target);
        targetValue->setObjectName(QStringLiteral("targetValue"));
        targetValue->setGeometry(QRect(50, 30, 70, 41));
        targetValue->setFont(font3);
        targetValue->setAlignment(Qt::AlignCenter);
        targetPlus = new QPushButton(target);
        targetPlus->setObjectName(QStringLiteral("targetPlus"));
        targetPlus->setGeometry(QRect(10, 30, 31, 31));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::Button, brush);
        QBrush brush1(QColor(85, 0, 127, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette25.setBrush(QPalette::Active, QPalette::Light, brush1);
        QBrush brush2(QColor(85, 0, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette25.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        QBrush brush3(QColor(0, 170, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette25.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette25.setBrush(QPalette::Active, QPalette::Base, brush);
        palette25.setBrush(QPalette::Active, QPalette::Window, brush);
        QBrush brush4(QColor(0, 85, 255, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette25.setBrush(QPalette::Active, QPalette::Shadow, brush4);
        QBrush brush5(QColor(170, 255, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette25.setBrush(QPalette::Active, QPalette::AlternateBase, brush5);
        palette25.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette25.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette25.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::Shadow, brush4);
        palette25.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush5);
        palette25.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette25.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        QBrush brush6(QColor(159, 158, 158, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette25.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette25.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette25.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette25.setBrush(QPalette::Disabled, QPalette::Shadow, brush4);
        palette25.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush5);
        targetPlus->setPalette(palette25);
        QFont font4;
        font4.setPointSize(14);
        font4.setBold(false);
        font4.setWeight(50);
        targetPlus->setFont(font4);
        targetPlus->setFocusPolicy(Qt::NoFocus);
        targetPlus->setAutoFillBackground(false);
        targetPlus->setAutoDefault(false);
        targetMinus = new QPushButton(target);
        targetMinus->setObjectName(QStringLiteral("targetMinus"));
        targetMinus->setGeometry(QRect(130, 30, 31, 31));
        targetMinus->setFont(font4);
        targetMinus->setFocusPolicy(Qt::NoFocus);
        map = new QFrame(centralWidget);
        map->setObjectName(QStringLiteral("map"));
        map->setGeometry(QRect(380, 330, 80, 80));
        map->setFrameShape(QFrame::StyledPanel);
        map->setFrameShadow(QFrame::Raised);
        mapLabel = new QLabel(map);
        mapLabel->setObjectName(QStringLiteral("mapLabel"));
        mapLabel->setGeometry(QRect(35, 10, 31, 16));
        mapIcon = new QPushButton(map);
        mapIcon->setObjectName(QStringLiteral("mapIcon"));
        mapIcon->setGeometry(QRect(10, 10, 21, 16));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::Button, brush);
        palette26.setBrush(QPalette::Active, QPalette::Base, brush);
        palette26.setBrush(QPalette::Active, QPalette::Window, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette26.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette26.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette26.setBrush(QPalette::Disabled, QPalette::Window, brush);
        mapIcon->setPalette(palette26);
        QIcon icon28;
        icon28.addFile(QStringLiteral(":/res/icon_blood_pressure.png"), QSize(), QIcon::Normal, QIcon::Off);
        mapIcon->setIcon(icon28);
        mapValue = new QLabel(map);
        mapValue->setObjectName(QStringLiteral("mapValue"));
        mapValue->setGeometry(QRect(10, 30, 61, 41));
        mapValue->setFont(font);
        mapValue->setAlignment(Qt::AlignCenter);
        bp = new QFrame(centralWidget);
        bp->setObjectName(QStringLiteral("bp"));
        bp->setGeometry(QRect(200, 330, 170, 80));
        bp->setFrameShape(QFrame::StyledPanel);
        bp->setFrameShadow(QFrame::Raised);
        bpLabel = new QLabel(bp);
        bpLabel->setObjectName(QStringLiteral("bpLabel"));
        bpLabel->setGeometry(QRect(110, 10, 31, 16));
        bpIcon = new QPushButton(bp);
        bpIcon->setObjectName(QStringLiteral("bpIcon"));
        bpIcon->setGeometry(QRect(60, 10, 21, 16));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::Button, brush);
        palette27.setBrush(QPalette::Active, QPalette::Base, brush);
        palette27.setBrush(QPalette::Active, QPalette::Window, brush);
        palette27.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette27.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette27.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette27.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette27.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette27.setBrush(QPalette::Disabled, QPalette::Window, brush);
        bpIcon->setPalette(palette27);
        bpIcon->setIcon(icon28);
        bpValue = new QLabel(bp);
        bpValue->setObjectName(QStringLiteral("bpValue"));
        bpValue->setGeometry(QRect(10, 30, 151, 41));
        bpValue->setFont(font);
        bpValue->setAlignment(Qt::AlignCenter);
        MainWindow->setCentralWidget(centralWidget);
        vitalsFrame->raise();
        frame_2->raise();
        startButton->raise();
        recalButton->raise();
        stopButton->raise();
        frame->raise();
        resp->raise();
        hr->raise();
        pulseRateLabel->raise();
        pulsePressureLabel->raise();
        batt->raise();
        snr->raise();
        cuff->raise();
        target->raise();
        map->raise();
        bp->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 477, 25));
        menuCaretaker_4_Demo_App = new QMenu(menuBar);
        menuCaretaker_4_Demo_App->setObjectName(QStringLiteral("menuCaretaker_4_Demo_App"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuCaretaker_4_Demo_App->menuAction());
        menuCaretaker_4_Demo_App->addAction(actionConnect);
        menuCaretaker_4_Demo_App->addAction(actionDisconnect);
        menuCaretaker_4_Demo_App->addAction(actionQuit);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        actionConnect->setText(QApplication::translate("MainWindow", "Connect", 0));
        actionDisconnect->setText(QApplication::translate("MainWindow", "Disconnect", 0));
        actionQuit->setText(QApplication::translate("MainWindow", "Quit", 0));
        startButton->setText(QApplication::translate("MainWindow", "Start", 0));
        recalButton->setText(QApplication::translate("MainWindow", "Recal", 0));
        stopButton->setText(QApplication::translate("MainWindow", "Stop", 0));
        pulseRateLabel->setText(QApplication::translate("MainWindow", "Pulse Rate", 0));
        pulsePressureLabel->setText(QApplication::translate("MainWindow", "Pulse Pressure", 0));
        respLabel->setText(QApplication::translate("MainWindow", "RESP", 0));
        respIcon->setText(QString());
        respValue->setText(QApplication::translate("MainWindow", "--", 0));
        hrLabel->setText(QApplication::translate("MainWindow", "HR", 0));
        hrIcon->setText(QString());
        hrValue->setText(QApplication::translate("MainWindow", "--", 0));
        battLabel->setText(QApplication::translate("MainWindow", "BATT", 0));
        battValue->setText(QApplication::translate("MainWindow", "0.0v", 0));
        battIconx->setText(QString());
        battIcon0->setText(QString());
        battIcon1->setText(QString());
        battIcon2->setText(QString());
        battIcon3->setText(QString());
        battIcon4->setText(QString());
        battIcon5->setText(QString());
        battIcon6->setText(QString());
        battIcon7->setText(QString());
        battIcon8->setText(QString());
        battIcon9->setText(QString());
        battIcon10->setText(QString());
        snrLabel->setText(QApplication::translate("MainWindow", "SNR", 0));
        snrValue->setText(QApplication::translate("MainWindow", "100%", 0));
        snrIcon0->setText(QString());
        snrIcon1->setText(QString());
        snrIcon2->setText(QString());
        snrIcon3->setText(QString());
        snrIcon4->setText(QString());
        snrIcon5->setText(QString());
        snrIcon6->setText(QString());
        snrIcon7->setText(QString());
        snrIcon8->setText(QString());
        snrIcon9->setText(QString());
        snrIcon10->setText(QString());
        cuffLabel->setText(QApplication::translate("MainWindow", "Cuff mmHg", 0));
        cuffValue->setText(QApplication::translate("MainWindow", "--", 0));
        targetLabel->setText(QApplication::translate("MainWindow", "Target mmHG", 0));
        targetValue->setText(QApplication::translate("MainWindow", "--", 0));
        targetPlus->setText(QApplication::translate("MainWindow", "+", 0));
        targetMinus->setText(QApplication::translate("MainWindow", "-", 0));
        mapLabel->setText(QApplication::translate("MainWindow", "MAP", 0));
        mapIcon->setText(QString());
        mapValue->setText(QApplication::translate("MainWindow", "--", 0));
        bpLabel->setText(QApplication::translate("MainWindow", "BP", 0));
        bpIcon->setText(QString());
        bpValue->setText(QApplication::translate("MainWindow", "--- / --", 0));
        menuCaretaker_4_Demo_App->setTitle(QApplication::translate("MainWindow", "Options", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
